/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.chan.drive;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TinyDriveApplicationTest {
    @Test void appHasAGreeting() {
        TinyDriveApplication classUnderTest = new TinyDriveApplication();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
