spring:
  profiles:
    active: local, test
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    generate-ddl: true
    show-sql: false

jwt:
  secret: ${JWT_SECRET}
  issuer: tiny-drive
  access-token-ttl: 30m

logging:
  level:
    org:
      springframework:
        security: DEBUG
---
spring:
  config:
    activate:
      on-profile: test

jwt:
  secret: 0zgxf/91cPc9P8pzfWrFgqAAkZHAXm1p9AAdPraPicx1Lv6085fUtrldJ7wgBSEuOkXh79U3R36owHipKAHYrw==
  issuer: tiny-drive
  access-token-ttl: 30m