/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.13/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("drive.spring-web")
    id("drive.spring-jpa")
    id("drive.lombok")
}

dependencies {
}

springBoot {
    mainClass.set("dev.chan.drive.TinyDriveApplication")
}
