/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.chan.drive;


import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class TinyDriveApplication {

    public static void main(String[] args) {
        SpringApplication.run(TinyDriveApplication.class, args);

    }
}
