/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.chan.drive;

public class TinyDriveApplication {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new TinyDriveApplication().getGreeting());
    }
}
