openapi: 3.1.0

info:
  title: Tiny Drive API
  description: Cloud기반 Dirve 스타일 문서 관리 시스템 API
  version: 0.1.0

servers:
  - url: http://localhost:8080
    description: Local development server

tags:
  - name: Items
    description: 파일/폴더 관리 API
  - name: Uploads
    description: 파일 업로드 API

paths: {}

components:
  schemas: {}
  responses: {}
  parameters: {}
  securitySchemes: {}